import { AttachmentBuilder, Colors, EmbedBuilder, SlashCommandBuilder, SlashCommandStringOption, SlashCommandSubcommandBuilder } from "discord.js";
import { Command } from "../classes/command";
import { CommandContext } from "../classes/commandContext";
import { Config } from "../types";
import { readFileSync } from "fs";

const config: Config = JSON.parse(readFileSync("config.json", "utf-8"))

const command_data = new SlashCommandBuilder()
    .setName("chat")
    .setDMPermission(false)
    .setDescription(`Start chatting with the AI`)
    .addSubcommand(
        new SlashCommandSubcommandBuilder()
        .setName("single")
        .setDescription("Get a single response without the possibility to followup")
        .addStringOption(
            new SlashCommandStringOption()
            .setName("message")
            .setDescription("The message to send to the AI")
            .setRequired(true)
            .setMaxLength(config?.generation_parameters?.max_input_chars ?? 10000)
        )
    )
    .addSubcommand(
        new SlashCommandSubcommandBuilder()
        .setName("thread")
        .setDescription("Start a thread for chatting with ChatGPT")
        .addStringOption(
            new SlashCommandStringOption()
            .setName("message")
            .setDescription("The message to send to the AI")
            .setRequired(true)
            .setMaxLength(config?.generation_parameters?.max_input_chars ?? 10000)
        )
    )


export default class extends Command {
    constructor() {
        super({
            name: "chat_single",
            command_data: command_data.toJSON(),
            staff_only: true,
        })
    }

    override async run(ctx: CommandContext): Promise<any> {
        if(!await ctx.client.checkConsent(ctx.interaction.user.id, ctx.database)) return ctx.error({error: `You need to agree to our ${await ctx.client.getSlashCommandTag("terms")} before using this command`, codeblock: false})
        if(!ctx.is_staff && ctx.client.config.global_user_cooldown && ctx.client.cooldown.has(ctx.interaction.user.id)) return ctx.error({error: "You are currently on cooldown"})
        const message = ctx.interaction.options.getString("message", true)
        const messages = []

        if(ctx.client.config.generation_parameters?.system_instruction?.length) messages.push({role: "system", content: ctx.client.config.generation_parameters?.system_instruction})

        messages.push({
            role: "user",
            content: message
        })

        await ctx.interaction.deferReply()

        if(await ctx.client.checkIfPromptGetsFlagged(message)) return ctx.error({error: "Your message has been flagged to be violating OpenAIs TOS"})

        const data = await ctx.client.requestChatCompletion(messages, ctx.interaction.user.id).catch(console.error)
        if(!data) return ctx.error({error: "Something went wrong"})

        if(ctx.client.config.dev) console.log(data)

        const description = `${message}\n\n**ChatGPT:**\n${data.choices[0]?.message.content ?? "Hi there"}`
        let payload = {}

        if(description.length < 4000) {
            const embed = new EmbedBuilder({
                author: {
                    name: ctx.interaction.user.tag,
                    icon_url: ctx.interaction.user.displayAvatarURL()
                },
                description,
                color: Colors.Green,
                footer: {text: "This text has been generated by OpenAIs GPT-3.5 Model"}
            })

            payload = {embeds: [embed]}
        } else {
            const attachment = new AttachmentBuilder(Buffer.from(`${ctx.interaction.user.tag}:\n${message}\n\nChatGPT:\n${data.choices[0]?.message.content ?? "Hi there"}\n\nThis response has been generated using OpenAIs GPT-3.5 model`), {name: `${data.id}.txt`})
            payload = {
                content: "Result attached below",
                files: [attachment]
            }
        }

        if(ctx.client.config.global_user_cooldown) ctx.client.cooldown.set(ctx.interaction.user.id, Date.now(), ctx.client.config.global_user_cooldown)
        const res = await ctx.interaction.editReply(payload)

        if(ctx.client.config.dev) {
            const devembed = new EmbedBuilder({
                title: "Dev",
                description: `**ID** \`${data.id}\`
                
**Prompt Tokens** ${data.usage.prompt_tokens}
**Completion Tokens** ${data.usage.completion_tokens}
**Total Tokens** ${data.usage.total_tokens}`,
                color: Colors.Red
            })
            await res.reply({
                embeds: [devembed]
            })
        }
    }
}